#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...

  // Willem: in this case we just have the robot move forward a bit to demonstrate
  //         how the pre_autorun works.
  wait1Msec(2000);						// Robot waits for 2000 milliseconds before executing program

	// Move forward at half power for 3 seconds
	motor[rightMotor] = 60;		  // Motor on port2 is run at full (127) power forward
	motor[leftMotor]  = 60;		  // Motor on port3 is run at full (127) power forward
	wait1Msec(3000);			        // Robot runs previous code for 3000 milliseconds
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	//AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.

	// Willem:  We are going to make a pivot turn to the right followed by one to the left
	// Turn Right at full power for 0.75 seconds
	motor[rightMotor] = -127;		  // Motor on port2 is run at full (-127) power reverse
	motor[leftMotor]  = 127;			// Motor on port3 is run at full (127) power forward
	wait1Msec(750);					      // Robot runs previous code for 750 milliseconds before moving on

	// Turn Left at full power for 0.75 seconds
	motor[rightMotor] = 127;			// Motor on port2 is run at full (127) power forward
	motor[leftMotor]  = -127;		  // Motor on port3 is run at full (-127) power reverse
	wait1Msec(750);					      // Robot runs previous code for 750 milliseconds before moving on

	motor[rightMotor] = 0;
	motor[leftMotor] = 0;

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

	  // .....................................................................................
	  // Insert user code here. This is where you use the joystick values to update your motors, etc.
	  // .....................................................................................

	  //UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.

	  // Willem: We are just inserting a basic tank control remote program here to demonstrate how it works
	  //Driving Motor Control
    motor[leftMotor] = vexRT[Ch3] / 2;
    motor[rightMotor] = vexRT[Ch2] / 2;

	}
}
